apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ysbfek2aa-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ysbfek2aa-nodejs 
  name: ysbfek2aa-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ysbfek2aa-nodejs 
